In [88]:
import xarray as xr
import numpy as np

In [79]:
x = xr.DataArray(range(0,100),coords={'depth':range(0,100)})

In [3]:
x

<xarray.DataArray (depth: 100)>
array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99

In [49]:
windows = x.rolling(depth=11,center=True,min_periods=11).construct('window')
windows[0:5]


<xarray.DataArray (depth: 5, window: 11)>
array([[nan, nan, nan, nan, nan,  0.,  1.,  2.,  3.,  4.,  5.],
       [nan, nan, nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.],
       [nan, nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [nan, nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.],
       [nan,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4
Dimensions without coordinates: window

In [39]:
#get all the below data
windows_below = windows[:,6:]
windows_below

<xarray.DataArray (depth: 100, window: 5)>
array([[ 1.,  2.,  3.,  4.,  5.],
       [ 2.,  3.,  4.,  5.,  6.],
       [ 3.,  4.,  5.,  6.,  7.],
       [ 4.,  5.,  6.,  7.,  8.],
       [ 5.,  6.,  7.,  8.,  9.],
       [ 6.,  7.,  8.,  9., 10.],
       [ 7.,  8.,  9., 10., 11.],
       [ 8.,  9., 10., 11., 12.],
       [ 9., 10., 11., 12., 13.],
       [10., 11., 12., 13., 14.],
       [11., 12., 13., 14., 15.],
       [12., 13., 14., 15., 16.],
       [13., 14., 15., 16., 17.],
       [14., 15., 16., 17., 18.],
       [15., 16., 17., 18., 19.],
       [16., 17., 18., 19., 20.],
       [17., 18., 19., 20., 21.],
       [18., 19., 20., 21., 22.],
       [19., 20., 21., 22., 23.],
       [20., 21., 22., 23., 24.],
...
       [81., 82., 83., 84., 85.],
       [82., 83., 84., 85., 86.],
       [83., 84., 85., 86., 87.],
       [84., 85., 86., 87., 88.],
       [85., 86., 87., 88., 89.],
       [86., 87., 88., 89., 90.],
       [87., 88., 89., 90., 91.],
       [88., 89., 90., 91., 92.],
       [89., 90., 91., 92., 93.],
       [90., 91., 92., 93., 94.],
       [91., 92., 93., 94., 95.],
       [92., 93., 94., 95., 96.],
       [93., 94., 95., 96., 97.],
       [94., 95., 96., 97., 98.],
       [95., 96., 97., 98., 99.],
       [96., 97., 98., 99., nan],
       [97., 98., 99., nan, nan],
       [98., 99., nan, nan, nan],
       [99., nan, nan, nan, nan],
       [nan, nan, nan, nan, nan]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99
Dimensions without coordinates: window

In [56]:
bellow=windows_below.rolling(window=5,min_periods=3).mean()
bellow



<xarray.DataArray (depth: 100, window: 5)>
array([[ nan,  nan,  2. ,  2.5,  3. ],
       [ nan,  nan,  3. ,  3.5,  4. ],
       [ nan,  nan,  4. ,  4.5,  5. ],
       [ nan,  nan,  5. ,  5.5,  6. ],
       [ nan,  nan,  6. ,  6.5,  7. ],
       [ nan,  nan,  7. ,  7.5,  8. ],
       [ nan,  nan,  8. ,  8.5,  9. ],
       [ nan,  nan,  9. ,  9.5, 10. ],
       [ nan,  nan, 10. , 10.5, 11. ],
       [ nan,  nan, 11. , 11.5, 12. ],
       [ nan,  nan, 12. , 12.5, 13. ],
       [ nan,  nan, 13. , 13.5, 14. ],
       [ nan,  nan, 14. , 14.5, 15. ],
       [ nan,  nan, 15. , 15.5, 16. ],
       [ nan,  nan, 16. , 16.5, 17. ],
       [ nan,  nan, 17. , 17.5, 18. ],
       [ nan,  nan, 18. , 18.5, 19. ],
       [ nan,  nan, 19. , 19.5, 20. ],
       [ nan,  nan, 20. , 20.5, 21. ],
       [ nan,  nan, 21. , 21.5, 22. ],
...
       [ nan,  nan, 82. , 82.5, 83. ],
       [ nan,  nan, 83. , 83.5, 84. ],
       [ nan,  nan, 84. , 84.5, 85. ],
       [ nan,  nan, 85. , 85.5, 86. ],
       [ nan,  nan, 86. , 86.5, 87. ],
       [ nan,  nan, 87. , 87.5, 88. ],
       [ nan,  nan, 88. , 88.5, 89. ],
       [ nan,  nan, 89. , 89.5, 90. ],
       [ nan,  nan, 90. , 90.5, 91. ],
       [ nan,  nan, 91. , 91.5, 92. ],
       [ nan,  nan, 92. , 92.5, 93. ],
       [ nan,  nan, 93. , 93.5, 94. ],
       [ nan,  nan, 94. , 94.5, 95. ],
       [ nan,  nan, 95. , 95.5, 96. ],
       [ nan,  nan, 96. , 96.5, 97. ],
       [ nan,  nan, 97. , 97.5, 97.5],
       [ nan,  nan, 98. , 98. , 98. ],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99
Dimensions without coordinates: window

In [51]:
windows_above = windows[:,[4,3,2,1,0]]
windows_above

<xarray.DataArray (depth: 100, window: 5)>
array([[nan, nan, nan, nan, nan],
       [ 0., nan, nan, nan, nan],
       [ 1.,  0., nan, nan, nan],
       [ 2.,  1.,  0., nan, nan],
       [ 3.,  2.,  1.,  0., nan],
       [ 4.,  3.,  2.,  1.,  0.],
       [ 5.,  4.,  3.,  2.,  1.],
       [ 6.,  5.,  4.,  3.,  2.],
       [ 7.,  6.,  5.,  4.,  3.],
       [ 8.,  7.,  6.,  5.,  4.],
       [ 9.,  8.,  7.,  6.,  5.],
       [10.,  9.,  8.,  7.,  6.],
       [11., 10.,  9.,  8.,  7.],
       [12., 11., 10.,  9.,  8.],
       [13., 12., 11., 10.,  9.],
       [14., 13., 12., 11., 10.],
       [15., 14., 13., 12., 11.],
       [16., 15., 14., 13., 12.],
       [17., 16., 15., 14., 13.],
       [18., 17., 16., 15., 14.],
...
       [79., 78., 77., 76., 75.],
       [80., 79., 78., 77., 76.],
       [81., 80., 79., 78., 77.],
       [82., 81., 80., 79., 78.],
       [83., 82., 81., 80., 79.],
       [84., 83., 82., 81., 80.],
       [85., 84., 83., 82., 81.],
       [86., 85., 84., 83., 82.],
       [87., 86., 85., 84., 83.],
       [88., 87., 86., 85., 84.],
       [89., 88., 87., 86., 85.],
       [90., 89., 88., 87., 86.],
       [91., 90., 89., 88., 87.],
       [92., 91., 90., 89., 88.],
       [93., 92., 91., 90., 89.],
       [94., 93., 92., 91., 90.],
       [95., 94., 93., 92., 91.],
       [96., 95., 94., 93., 92.],
       [97., 96., 95., 94., 93.],
       [98., 97., 96., 95., 94.]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99
Dimensions without coordinates: window

In [54]:
above=windows_above.rolling(window=5,min_periods=3).mean()
above

<xarray.DataArray (depth: 100, window: 5)>
array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  1. ,  1. ,  1. ],
       [ nan,  nan,  2. ,  1.5,  1.5],
       [ nan,  nan,  3. ,  2.5,  2. ],
       [ nan,  nan,  4. ,  3.5,  3. ],
       [ nan,  nan,  5. ,  4.5,  4. ],
       [ nan,  nan,  6. ,  5.5,  5. ],
       [ nan,  nan,  7. ,  6.5,  6. ],
       [ nan,  nan,  8. ,  7.5,  7. ],
       [ nan,  nan,  9. ,  8.5,  8. ],
       [ nan,  nan, 10. ,  9.5,  9. ],
       [ nan,  nan, 11. , 10.5, 10. ],
       [ nan,  nan, 12. , 11.5, 11. ],
       [ nan,  nan, 13. , 12.5, 12. ],
       [ nan,  nan, 14. , 13.5, 13. ],
       [ nan,  nan, 15. , 14.5, 14. ],
       [ nan,  nan, 16. , 15.5, 15. ],
       [ nan,  nan, 17. , 16.5, 16. ],
...
       [ nan,  nan, 78. , 77.5, 77. ],
       [ nan,  nan, 79. , 78.5, 78. ],
       [ nan,  nan, 80. , 79.5, 79. ],
       [ nan,  nan, 81. , 80.5, 80. ],
       [ nan,  nan, 82. , 81.5, 81. ],
       [ nan,  nan, 83. , 82.5, 82. ],
       [ nan,  nan, 84. , 83.5, 83. ],
       [ nan,  nan, 85. , 84.5, 84. ],
       [ nan,  nan, 86. , 85.5, 85. ],
       [ nan,  nan, 87. , 86.5, 86. ],
       [ nan,  nan, 88. , 87.5, 87. ],
       [ nan,  nan, 89. , 88.5, 88. ],
       [ nan,  nan, 90. , 89.5, 89. ],
       [ nan,  nan, 91. , 90.5, 90. ],
       [ nan,  nan, 92. , 91.5, 91. ],
       [ nan,  nan, 93. , 92.5, 92. ],
       [ nan,  nan, 94. , 93.5, 93. ],
       [ nan,  nan, 95. , 94.5, 94. ],
       [ nan,  nan, 96. , 95.5, 95. ],
       [ nan,  nan, 97. , 96.5, 96. ]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99
Dimensions without coordinates: window

In [61]:
# swap it back round so that 1st position = max number of items   5 4 3 2 1
# first position in below = 1 item                                1 2 3 4 5
# note that less than 2 items can't be and we need 3 then only 3 3 works
bove=above[:,[4,3,2,1,0]]
above

<xarray.DataArray (depth: 100, window: 5)>
array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ 1. ,  1. ,  1. ,  nan,  nan],
       [ 1.5,  1.5,  2. ,  nan,  nan],
       [ 2. ,  2.5,  3. ,  nan,  nan],
       [ 3. ,  3.5,  4. ,  nan,  nan],
       [ 4. ,  4.5,  5. ,  nan,  nan],
       [ 5. ,  5.5,  6. ,  nan,  nan],
       [ 6. ,  6.5,  7. ,  nan,  nan],
       [ 7. ,  7.5,  8. ,  nan,  nan],
       [ 8. ,  8.5,  9. ,  nan,  nan],
       [ 9. ,  9.5, 10. ,  nan,  nan],
       [10. , 10.5, 11. ,  nan,  nan],
       [11. , 11.5, 12. ,  nan,  nan],
       [12. , 12.5, 13. ,  nan,  nan],
       [13. , 13.5, 14. ,  nan,  nan],
       [14. , 14.5, 15. ,  nan,  nan],
       [15. , 15.5, 16. ,  nan,  nan],
       [16. , 16.5, 17. ,  nan,  nan],
...
       [77. , 77.5, 78. ,  nan,  nan],
       [78. , 78.5, 79. ,  nan,  nan],
       [79. , 79.5, 80. ,  nan,  nan],
       [80. , 80.5, 81. ,  nan,  nan],
       [81. , 81.5, 82. ,  nan,  nan],
       [82. , 82.5, 83. ,  nan,  nan],
       [83. , 83.5, 84. ,  nan,  nan],
       [84. , 84.5, 85. ,  nan,  nan],
       [85. , 85.5, 86. ,  nan,  nan],
       [86. , 86.5, 87. ,  nan,  nan],
       [87. , 87.5, 88. ,  nan,  nan],
       [88. , 88.5, 89. ,  nan,  nan],
       [89. , 89.5, 90. ,  nan,  nan],
       [90. , 90.5, 91. ,  nan,  nan],
       [91. , 91.5, 92. ,  nan,  nan],
       [92. , 92.5, 93. ,  nan,  nan],
       [93. , 93.5, 94. ,  nan,  nan],
       [94. , 94.5, 95. ,  nan,  nan],
       [95. , 95.5, 96. ,  nan,  nan],
       [96. , 96.5, 97. ,  nan,  nan]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99
Dimensions without coordinates: window

In [67]:
above

<xarray.DataArray (depth: 100, window: 5)>
array([[ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ nan,  nan,  nan,  nan,  nan],
       [ 1. ,  1. ,  1. ,  nan,  nan],
       [ 1.5,  1.5,  2. ,  nan,  nan],
       [ 2. ,  2.5,  3. ,  nan,  nan],
       [ 3. ,  3.5,  4. ,  nan,  nan],
       [ 4. ,  4.5,  5. ,  nan,  nan],
       [ 5. ,  5.5,  6. ,  nan,  nan],
       [ 6. ,  6.5,  7. ,  nan,  nan],
       [ 7. ,  7.5,  8. ,  nan,  nan],
       [ 8. ,  8.5,  9. ,  nan,  nan],
       [ 9. ,  9.5, 10. ,  nan,  nan],
       [10. , 10.5, 11. ,  nan,  nan],
       [11. , 11.5, 12. ,  nan,  nan],
       [12. , 12.5, 13. ,  nan,  nan],
       [13. , 13.5, 14. ,  nan,  nan],
       [14. , 14.5, 15. ,  nan,  nan],
       [15. , 15.5, 16. ,  nan,  nan],
       [16. , 16.5, 17. ,  nan,  nan],
...
       [77. , 77.5, 78. ,  nan,  nan],
       [78. , 78.5, 79. ,  nan,  nan],
       [79. , 79.5, 80. ,  nan,  nan],
       [80. , 80.5, 81. ,  nan,  nan],
       [81. , 81.5, 82. ,  nan,  nan],
       [82. , 82.5, 83. ,  nan,  nan],
       [83. , 83.5, 84. ,  nan,  nan],
       [84. , 84.5, 85. ,  nan,  nan],
       [85. , 85.5, 86. ,  nan,  nan],
       [86. , 86.5, 87. ,  nan,  nan],
       [87. , 87.5, 88. ,  nan,  nan],
       [88. , 88.5, 89. ,  nan,  nan],
       [89. , 89.5, 90. ,  nan,  nan],
       [90. , 90.5, 91. ,  nan,  nan],
       [91. , 91.5, 92. ,  nan,  nan],
       [92. , 92.5, 93. ,  nan,  nan],
       [93. , 93.5, 94. ,  nan,  nan],
       [94. , 94.5, 95. ,  nan,  nan],
       [95. , 95.5, 96. ,  nan,  nan],
       [96. , 96.5, 97. ,  nan,  nan]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99
Dimensions without coordinates: window

In [78]:
x

<xarray.DataArray (depth: 100)>
array([  0,   1, 200,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99

In [82]:
# ok make shure that only index 5 will be greater
y = x-5
y[5]=200

In [100]:
# compare above and below
output =(above<(y))&(bellow<(y))

In [101]:
output

<xarray.DataArray (depth: 100, window: 5)>
array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
...
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99
Dimensions without coordinates: window

In [102]:
#now collaps the matrix
output.max(dim='window')

<xarray.DataArray (depth: 100)>
array([False, False, False, False, False,  True, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False])
Coordinates:
  * depth    (depth) int64 0 1 2 3 4 5 6 7 8 9 ... 90 91 92 93 94 95 96 97 98 99